# Generated by Django 5.2.1 on 2025-05-21 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_remove_user_accountcreated_user_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='accountCreated',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
